name: Deploy to AWS (CDK)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Optional: CDK bootstrap (only needed once per account/region)
      # - name: Bootstrap CDK
      #   run: npx cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION

      - name: Deploy CDK stack
        run: npx cdk deploy --require-approval never
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.BETA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
